name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package build files
        run: |
          mkdir -p dist
          zip -r dist/build-${{ github.sha }}.zip dist

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(npm show <package-name> version)"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.THE_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Package version: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist/build-${{ github.sha }}.zip
